# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KszkEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_of_pers', models.IntegerField()),
                ('visitors', models.ManyToManyField(related_name='visitor', to='account.Profile')),
            ],
        ),
    ]
