# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kepzes_alkalom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idopont', models.DateField()),
                ('letszam', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='felhaszbalo_nev',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='year_of_kepzes',
            new_name='kepzes_eve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='megjegyzes',
        ),
        migrations.AddField(
            model_name='kepzes_alkalom',
            name='resztvevok',
            field=models.ManyToManyField(to='stats.User'),
        ),
    ]
