# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_group',
            field=models.CharField(choices=[('DT', 'DevTeam'), ('NET', 'NeTeam'), ('ST', 'SecurITeam'), ('SYS', 'SysAdmin'), ('N', 'None')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='kszkevent',
            name='visitors',
            field=models.ManyToManyField(related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
