# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kszkevent',
            name='num_of_pers',
            field=models.IntegerField(editable=False),
        ),
    ]
