# Generated by Django 2.0.1 on 2019-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190122_1341'),
        ('stats', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='absent',
            field=models.ManyToManyField(
                blank=True, related_name='events_absent', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visitors',
            field=models.ManyToManyField(
                blank=True, related_name='events_visitor', to='account.Profile'),
        ),
    ]
