# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20171111_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kszkevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
