# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170925_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='felhaszbalo_nev',
            new_name='felhasznalo_nev',
        ),
    ]
