# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0003_auto_20170925_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kszk_training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_of_pers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_join', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kepzes_alkalom',
            name='resztvevok',
        ),
        migrations.DeleteModel(
            name='Kepzes_alkalom',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kszk_training',
            name='visitors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
