# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20171114_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kszkevent',
            name='num_of_pers',
        ),
    ]
