# Generated by Django 2.0.1 on 2018-02-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180205_2004'),
        ('stats', '0004_remove_kszkevent_num_of_pers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('visitors', models.ManyToManyField(related_name='visitor', to='account.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='kszkevent',
            name='visitors',
        ),
        migrations.DeleteModel(
            name='KszkEvent',
        ),
    ]
