# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170925_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kszk_training',
            new_name='Event',
        ),
    ]
