# Generated by Django 2.0.1 on 2018-02-14 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180214_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visitors',
            field=models.ManyToManyField(related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
