# Generated by Django 2.2.4 on 2020-02-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20200209_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='mentor',
        ),
    ]
