# Generated by Django 2.0.1 on 2019-01-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190113_1239'),
        ('document', '0002_auto_20190113_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='homework.Solution'),
        ),
    ]
