# Generated by Django 2.0.1 on 2019-01-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20190121_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='solution',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='files', to='homework.Solution'),
        ),
    ]
