# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171114_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
