# Generated by Django 2.2.4 on 2020-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190122_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images/'),
        ),
    ]
