# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
