# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
