# Generated by Django 2.2.4 on 2020-02-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
