# Generated by Django 2.2.4 on 2020-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200202_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadline',
            old_name='text',
            new_name='messageAfter',
        ),
        migrations.AddField(
            model_name='deadline',
            name='messageBefore',
            field=models.TextField(blank=True, default=''),
        ),
    ]
