# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171223_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_group', models.CharField(choices=[('DT', 'DevTeam'), ('NET', 'NeTeam'), ('ST', 'SecurITeam'), ('SYS', 'SysAdmin'), ('HAT', 'Hallgatói Tudásbázis'), ('N', 'None')], default='None', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pref_group',
        ),
        migrations.AddField(
            model_name='groupchoice',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferd_groups', to='account.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchoice',
            unique_together=set([('pref_group', 'profile')]),
        ),
    ]
