# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180124_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='motivation',
            field=models.TextField(null=True),
        ),
    ]
