# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='profiles', to='account.GroupChoice'),
        ),
        migrations.AlterField(
            model_name='groupchoice',
            name='choice',
            field=models.CharField(choices=[('DT', 'DevTeam'), ('NET', 'NeTeam'), ('ST', 'SecurITeam'), ('SYS', 'SysAdmin'), ('HAT', 'Hallgatói Tudásbázis'), ('N', 'None')], default='N', max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='groupchoice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupchoice',
            name='profile',
        ),
    ]
