# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
