# Generated by Django 2.0.1 on 2018-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180203_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
