# Generated by Django 2.0.1 on 2018-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180203_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='motivation',
            new_name='motivation_about',
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation_exercise',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation_profession',
            field=models.TextField(blank=True, default=''),
        ),
    ]
