# Generated by Django 2.2.4 on 2020-02-02 14:41

import common.middleware
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(default=common.middleware.CurrentUserMiddleware.get_current_user_profile,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater', to='account.Profile'),
        ),
    ]
