# Generated by Django 2.0.1 on 2018-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='ready',
        ),
        migrations.AlterField(
            model_name='solution',
            name='accepted',
            field=models.BooleanField(),
        ),
    ]
