# Generated by Django 2.2.4 on 2020-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20190121_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solution',
            name='accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='corrected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
