# Generated by Django 2.0.1 on 2019-01-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20190105_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='files',
        ),
        migrations.AlterField(
            model_name='solution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solution', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='homework.Task'),
        ),
    ]
