# Generated by Django 2.0.1 on 2019-01-14 15:41

import common.middleware
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190113_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='created_by',
            field=models.ForeignKey(default=common.middleware.CurrentUserMiddleware.get_current_user_profile, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solution', to='account.Profile'),
        ),
    ]
