# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20180204_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='date',
            new_name='alma',
        ),
    ]
