# Generated by Django 2.0.1 on 2019-01-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20190114_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
