# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20180204_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='alma',
            new_name='date',
        ),
    ]
