# Generated by Django 2.0.1 on 2018-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20180204_1601'),
        ('homework', '0005_auto_20180126_0135'),
    ]

    operations = [
    ]
