# Generated by Django 2.0.1 on 2018-02-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_merge_20180209_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_solution', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Profile'),
        ),
    ]
