# Generated by Django 2.0.1 on 2018-04-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_auto_20180221_1135'),
        ('homework', '0007_merge_20180205_2021'),
    ]

    operations = [
    ]
